spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenhai2000/springcloud_sell_test.git
          username: zhuwenhai0826@foxmail.com
          password: englih0826
          basedir: F:\demo\SpringCloud_Sell\config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"